# Generated by Django 3.1.2 on 2020-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
