# Generated by Django 3.1.4 on 2020-12-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bargain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='watches',
            new_name='watch',
        ),
    ]
