from matematical_operations.operations import divide_numbers, multiply_numbers, subtract_numbers, sum_numbers, raise_numbers
from matematical_operations.calculate_result import calculate_two_numbers

