# Generated by Django 3.1.3 on 2020-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
