# Generated by Django 4.0.4 on 2022-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
