# Generated by Django 3.1.3 on 2020-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_advanced_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='image_url',
            field=models.URLField(),
        ),
    ]
