# Generated by Django 3.1.3 on 2020-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_advanced_app', '0002_auto_20201113_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='image_url',
        ),
        migrations.AddField(
            model_name='python',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
