# Generated by Django 3.1.3 on 2020-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_advanced_app', '0004_python_snake_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='image',
            field=models.ImageField(upload_to='public/images'),
        ),
        migrations.AlterField(
            model_name='python',
            name='snake_passport',
            field=models.FileField(upload_to='private/snake_documents'),
        ),
    ]
