# Generated by Django 3.1.3 on 2020-11-22 10:00

from django.db import migrations, models
import templates_advanced_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_advanced_app', '0005_auto_20201114_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='snake_passport',
            field=models.FileField(upload_to='private/snake_documents', validators=[templates_advanced_app.models.is_zip_validator]),
        ),
    ]
