# Generated by Django 3.1.3 on 2020-11-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates_advanced_app', '0006_auto_20201122_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='python',
            name='created_by_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
