# Generated by Django 3.1.3 on 2020-11-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_advanced_app', '0007_python_created_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='python',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
